name: production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - scanner-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build new image
        run: |
          docker build ./ -t scanner-scan:latest
